### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by martab0** [AFAFAF1357/MARKDOWN#1]
Jest repozytorium, jest Markdown, jest dobrze :)
W miarę wolnego czasu uzupełnij brakujące elementy składni, np. listę numerowaną i punkty, zrób rozdziały i odśwież spis treści. Przyda się na zajęciach pod koniec semestru!

**Comment by AFAFAF1357** [comment]
Długo walczyłam ze spisem treści. Efekt jest taki, że się aktualizuje, ale nie potrafię pozbyć się punktorów w spisie treści. Chciałabym mieć listę numerowaną, bez tych kropek.

**Comment by martab0** [comment]
"Z głowy" nie przypomnę sobie, jak zrobić spis treści bez punktorów :) Postaram się pamiętać też o tym na zajęciach 25-26 lutego. Przypomnij, proszę :)
