### ISSUE TITLE
Image

### ISSUE THREAD

**Issue by martab0** [AFAFAF1357/MARKDOWN#2]
Sprawdź, dlaczego działa odsyłacz do obrazka z Internetu, a nie działa odsyłacz do Twojego pliku graficznego - i popraw to!

**Comment by AFAFAF1357** [comment]
Powalczyłam z różnymi typami plików, efekt widoczny w pliku praca domowa v2.md. Ku memu zdziwieniu nie działa pdf. Nie działa też tiff, ale to chyba kwestia rozmiaru pliku - mam komunikat (Sorry about that, but we can’t show files that are this big right now.)

**Comment by martab0** [comment]
Racja - nie wszystkie pliki graficzne dają się wstawić jako obrazek, a PDF nie jest tu traktowany jak plik graficzny.
Zrobiłaś świetny test!
Więcej informacji: https://docs.github.com/en/repositories/working-with-files/using-files/working-with-non-code-files
Postaram się pamiętać, żeby zahaczyć o załączanie PDF-ów na zajęciach 25-26 lutego!
