### ISSUE TITLE
STE

### ISSUE THREAD

**Issue by martab0** [AFAFAF1357/MARKDOWN#21]
Tekst od początku był napisany w miarę zgodnie z STE, dlatego nie wymagał dużych zmian. Te zmiany, które zrobiłaś, są bardzo dobre (również w kierunku internacjonalizacji, np. jednostki miary).
Można ewentualnie doprecyzować punkt 6, np. wstawić dwie metody zwilżania szczoteczki jako podpunkty (bullet points) :)

Now wet the toothbrush in one of the following ways:
* Place the toothbrush under the tap and turn on water for a second. Turn off the water. 
* Rinse the toothbrush in a cup of water.

**Comment by AFAFAF1357** [comment]
Zmienione!
